# This workflow will use Nox to run tests and lint for the supported Python versions, and upload the test coverage data.

name: Build & Test

on:
    push:
        branches:
            - main
            - release/*
        paths:
            - "constraint/**"
            - "tests/**"
            - "cythonize_build.py"
            - "noxfile.py"
            - "pyproject.toml"
            - ".github/workflows/build-test-python-package.yml"
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: fjwillemsen/setup-nox2@v3.0.0
            - run: |
                  nox -- ${{ runner.os }}
            - name: Store benchmark result
              uses: benchmark-action/github-action-benchmark@v1
              with:
                  tool: "pytest"
                  output-file-path: .benchmarks/benchmark_${{ runner.os }}_3.13.json
                  gh-pages-branch: main
                  benchmark-data-dir-path: docs/benchmarks
                  fail-on-alert: true
                  # GitHub API token to make a commit comment
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  auto-push: true
                  comment-on-alert: true
                  comment-always: true
                  #   alert-comment-cc-users: '@fjwillemsen' mention a GitHub user in the comment
            - name: Report to Coveralls
              uses: coverallsapp/github-action@v2
              with:
                  file: coverage.xml
                  format: cobertura
                  fail-on-error: false
